name: My Github Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build --no-daemon
      - name: Send Webhook on Success or Failure
        if: success() || failure()
        run: |
          if [ ${{ success() }} == true ]; then
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"content\": \"Build Success\"}" \
              ${{ secrets.DISCORDE_WEBHOOK_URL}}
          else
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"content\": \"Build Failure\"}" \
              ${{ secrets.DISCORDE_WEBHOOK_URL}}
          fi
